// ============================================================
// INSTRUMENTS DATA — 16 instruments with real teaching images
// Source: ChineseLearningTeaching/Chinese Teaching/乐器.ppt
// Images: /public/images/instruments/
// Mix of Chinese traditional + Western (matches teaching material)
// ============================================================

// Color/accent palette by category
const PALETTE = {
  chinese:    { color: "#E8F2E0", accent: "#5C8348" }, // jade green
  strings:    { color: "#F8E2DE", accent: "#A04A3B" }, // red wood
  keyboard:   { color: "#EDE8FA", accent: "#5E4A9A" }, // ink purple
  wind:       { color: "#FFF1CC", accent: "#A6792C" }, // bronze
  electronic: { color: "#E4ECF8", accent: "#4A6890" }, // steel blue
};

export const INSTRUMENTS = [
  {
    id: "piano",
    zh: "钢琴",
    pinyin: "gāng qín",
    name: "Piano",
    category: "Keyboard",
    img: "/images/instruments/01_钢琴.png",
    ...PALETTE.keyboard,
    description: "A piano has 88 black and white keys — pressing them swings hammers that strike strings inside.",
    question: "How many keys does a standard piano have?",
    options: ["88", "24", "100"],
    answer: "88",
    feedback: "Yes! 88 keys — 52 white and 36 black.",
  },
  {
    id: "violin",
    zh: "小提琴",
    pinyin: "xiǎo tí qín",
    name: "Violin",
    category: "Western strings",
    img: "/images/instruments/02_小提琴.png",
    ...PALETTE.strings,
    description: "Held under the chin and played with a bow drawn across four strings.",
    question: "How is a violin usually played?",
    options: ["With a bow across the strings", "Plucked only", "Hit with a small mallet"],
    answer: "With a bow across the strings",
    feedback: "Right! The bow makes the strings sing.",
  },
  {
    id: "viola",
    zh: "中提琴",
    pinyin: "zhōng tí qín",
    name: "Viola",
    category: "Western strings",
    img: "/images/instruments/03_中提琴.png",
    ...PALETTE.strings,
    description: "Looks like a bigger violin — its voice is deeper and warmer.",
    question: "Compared with a violin, a viola is…",
    options: ["A little bigger and deeper", "Smaller and higher", "Exactly the same"],
    answer: "A little bigger and deeper",
    feedback: "Yes! The viola sits between the violin and the cello.",
  },
  {
    id: "cello",
    zh: "大提琴",
    pinyin: "dà tí qín",
    name: "Cello",
    category: "Western strings",
    img: "/images/instruments/04_大提琴.png",
    ...PALETTE.strings,
    description: "Sits on the floor between the player's knees — its low voice sounds almost like singing.",
    question: "How do you hold a cello when you play?",
    options: ["On the floor between your knees", "Under your chin", "Standing on your shoulder"],
    answer: "On the floor between your knees",
    feedback: "Correct! A small endpin rests on the floor.",
  },
  {
    id: "accordion",
    zh: "手风琴",
    pinyin: "shǒu fēng qín",
    name: "Accordion",
    category: "Wind / Keyboard",
    img: "/images/instruments/05_手风琴.png",
    ...PALETTE.wind,
    description: "Squeeze and stretch the bellows while pressing keys — like a portable mini-band.",
    question: "How does an accordion make sound?",
    options: ["Bellows push air past metal reeds", "Plucking strings", "Hitting drums"],
    answer: "Bellows push air past metal reeds",
    feedback: "Yes! Air through reeds is what creates the music.",
  },
  {
    id: "harmonica",
    zh: "口琴",
    pinyin: "kǒu qín",
    name: "Harmonica",
    category: "Wind",
    img: "/images/instruments/06_口琴.png",
    ...PALETTE.wind,
    description: "Tiny and pocket-sized — you blow and draw air through holes to make different notes.",
    question: "How do you play a harmonica?",
    options: ["Blow and draw air through it", "Bow it with a horsehair bow", "Pluck its strings"],
    answer: "Blow and draw air through it",
    feedback: "Right! Blowing and drawing each give different notes.",
  },
  {
    id: "organ",
    zh: "风琴",
    pinyin: "fēng qín",
    name: "Organ",
    category: "Keyboard",
    img: "/images/instruments/07_风琴.png",
    ...PALETTE.keyboard,
    description: "A keyboard instrument whose tone is made by pushing air through pipes or reeds.",
    question: "Where does an organ's sound come from?",
    options: ["Air pushed through pipes / reeds", "Hammers hitting strings", "Drum skins"],
    answer: "Air pushed through pipes / reeds",
    feedback: "Yes! That's why organs can be so powerful.",
  },
  {
    id: "yangqin",
    zh: "扬琴",
    pinyin: "yáng qín",
    name: "Yangqin",
    category: "Chinese traditional",
    img: "/images/instruments/08_扬琴.png",
    ...PALETTE.chinese,
    description: "A Chinese hammered dulcimer — you tap the strings with two thin bamboo mallets.",
    question: "How is the yangqin played?",
    options: ["Tap the strings with bamboo mallets", "Blow into a mouthpiece", "Bow it like a violin"],
    answer: "Tap the strings with bamboo mallets",
    feedback: "Right! Two light mallets make its sparkling sound.",
  },
  {
    id: "harp",
    zh: "竖琴",
    pinyin: "shù qín",
    name: "Harp",
    category: "Western strings",
    img: "/images/instruments/09_竖琴.png",
    ...PALETTE.strings,
    description: "A tall, triangular instrument with many strings — played by plucking with the fingers.",
    question: "How is a harp played?",
    options: ["Plucking the strings with fingers", "Hitting keys", "Blowing through a mouthpiece"],
    answer: "Plucking the strings with fingers",
    feedback: "Yes! Both hands pluck the strings.",
  },
  {
    id: "keyboard",
    zh: "电子琴",
    pinyin: "diàn zǐ qín",
    name: "Electronic Keyboard",
    category: "Electronic",
    img: "/images/instruments/10_电子琴.png",
    ...PALETTE.electronic,
    description: "A modern electronic keyboard that can imitate many other instrument sounds.",
    question: "What makes an electronic keyboard special?",
    options: ["It can mimic many instrument sounds", "It has 200 real strings", "It works without electricity"],
    answer: "It can mimic many instrument sounds",
    feedback: "Right! Piano, organ, strings — it can be all of them.",
  },
  {
    id: "dizi",
    zh: "笛子",
    pinyin: "dí zi",
    name: "Dizi (Bamboo Flute)",
    category: "Chinese traditional",
    img: "/images/instruments/11_笛子.png",
    ...PALETTE.chinese,
    description: "A Chinese bamboo flute with a thin paper-like membrane that gives it a bright, buzzing voice.",
    question: "What's special about a dizi?",
    options: ["A buzzing membrane gives it a bright tone", "It has 88 keys", "It's made of metal"],
    answer: "A buzzing membrane gives it a bright tone",
    feedback: "Yes! The membrane (笛膜) is the secret to its voice.",
  },
  {
    id: "clarinet",
    zh: "黑管",
    pinyin: "hēi guǎn",
    name: "Clarinet",
    category: "Wind",
    img: "/images/instruments/12_黑管.png",
    ...PALETTE.wind,
    description: "A black wooden woodwind instrument with a small reed in its mouthpiece.",
    question: "What's inside a clarinet's mouthpiece?",
    options: ["A thin reed", "A bell", "A string"],
    answer: "A thin reed",
    feedback: "Correct! The reed vibrates against the mouthpiece.",
  },
  {
    id: "side-flute",
    zh: "横笛",
    pinyin: "héng dí",
    name: "Side-blown Flute",
    category: "Wind",
    img: "/images/instruments/13_横笛.png",
    ...PALETTE.wind,
    description: "Held sideways — you blow across a hole near the top, like a Western flute.",
    question: "How do you hold a 横笛 (side-blown flute)?",
    options: ["Sideways across your lips", "Straight down", "Straight up"],
    answer: "Sideways across your lips",
    feedback: "Yes! 横 (héng) means 'sideways'.",
  },
  {
    id: "erhu",
    zh: "二胡",
    pinyin: "èr hú",
    name: "Erhu",
    category: "Chinese traditional",
    img: "/images/instruments/14_二胡.png",
    ...PALETTE.chinese,
    description: "A Chinese two-string fiddle whose singing voice can sound almost human.",
    question: "How many strings does the erhu have?",
    options: ["Two", "Six", "Twelve"],
    answer: "Two",
    feedback: "Right! 二 means 'two' — just two strings.",
  },
  {
    id: "pipa",
    zh: "琵琶",
    pinyin: "pí pá",
    name: "Pipa",
    category: "Chinese traditional",
    img: "/images/instruments/15_琵琶.png",
    ...PALETTE.chinese,
    description: "A pear-shaped Chinese lute, played upright on the lap by plucking with the fingers.",
    question: "What shape is the body of a pipa?",
    options: ["Pear-shaped", "Triangle", "Square"],
    answer: "Pear-shaped",
    feedback: "Yes! That classic pear shape is unmistakable.",
  },
  {
    id: "trumpet",
    zh: "小号",
    pinyin: "xiǎo hào",
    name: "Trumpet",
    category: "Wind",
    img: "/images/instruments/16_小号.png",
    ...PALETTE.wind,
    description: "A bright, golden brass instrument — you buzz your lips into the mouthpiece.",
    question: "How do you sound a trumpet?",
    options: ["Buzz your lips into the mouthpiece", "Strum the strings", "Hit it with a stick"],
    answer: "Buzz your lips into the mouthpiece",
    feedback: "Correct! Lip vibration is what makes the sound.",
  },
];

// Pick `n` shuffled distinct options including the correct one
export function quizOptionsFor(correctItem, all = INSTRUMENTS, n = 4) {
  const others = all.filter((x) => x.id !== correctItem.id);
  for (let i = others.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [others[i], others[j]] = [others[j], others[i]];
  }
  const picks = [correctItem, ...others.slice(0, n - 1)];
  for (let i = picks.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [picks[i], picks[j]] = [picks[j], picks[i]];
  }
  return picks;
}
