// ============================================================
// INSTRUMENTS DATA — Six traditional Chinese instruments
// Categories covered: plucked / bowed / wind / percussion
// ============================================================

export const INSTRUMENTS = [
  {
    id: "guqin",
    emoji: "🎼",
    name: "Guqin",
    zh: "古琴",
    category: "Plucked zither",
    color: "#EDE8FA",
    accent: "#5E4A9A",
    description: "A seven-string zither played by scholars for 3000+ years.",
    question: "What does the Guqin look like?",
    options: ["A long wooden zither", "A round drum", "A brass horn"],
    answer: "A long wooden zither",
    feedback: "Yes! The Guqin is a long, slim wooden zither — a symbol of refined learning.",
  },
  {
    id: "pipa",
    emoji: "🪕",
    name: "Pipa",
    zh: "琵琶",
    category: "Plucked lute",
    color: "#FBEEDB",
    accent: "#A26835",
    description: "A pear-shaped lute with four strings, played upright on the lap.",
    question: "How is the Pipa played?",
    options: ["Plucked with fingers", "Blown with breath", "Hit with sticks"],
    answer: "Plucked with fingers",
    feedback: "Right! The name 'Pipa' even comes from the sound of plucking motions.",
  },
  {
    id: "erhu",
    emoji: "🎻",
    name: "Erhu",
    zh: "二胡",
    category: "Bowed string",
    color: "#F8E2DE",
    accent: "#A04A3B",
    description: "A two-string fiddle with a singing voice that can sound almost human.",
    question: "How many strings does the Erhu have?",
    options: ["Two", "Six", "Twelve"],
    answer: "Two",
    feedback: "Correct! Just two strings and a bow — yet it can express deep emotion.",
  },
  {
    id: "dizi",
    emoji: "🪈",
    name: "Dizi",
    zh: "笛子",
    category: "Bamboo flute",
    color: "#E8F2E0",
    accent: "#5C8348",
    description: "A bamboo flute with a buzzing membrane that gives it a bright voice.",
    question: "What is the Dizi made of?",
    options: ["Bamboo", "Iron", "Glass"],
    answer: "Bamboo",
    feedback: "Yes! Bamboo with a thin paper-like membrane that buzzes when you blow.",
  },
  {
    id: "guzheng",
    emoji: "🎶",
    name: "Guzheng",
    zh: "古筝",
    category: "Plucked zither",
    color: "#FAE6EC",
    accent: "#A04E73",
    description: "A long zither with movable bridges — often used in flowing solo music.",
    question: "How many strings does a modern Guzheng usually have?",
    options: ["21", "4", "88"],
    answer: "21",
    feedback: "Right! The modern Guzheng has 21 strings tuned in a pentatonic scale.",
  },
  {
    id: "luo",
    emoji: "🔔",
    name: "Luo",
    zh: "锣",
    category: "Percussion gong",
    color: "#FFF1CC",
    accent: "#A6792C",
    description: "A round bronze gong struck with a soft mallet — a heartbeat of festivals.",
    question: "How do you play the Luo (gong)?",
    options: ["Strike it with a mallet", "Pluck the strings", "Blow into it"],
    answer: "Strike it with a mallet",
    feedback: "Yes! A soft mallet brings out its big, resonant voice.",
  },
];
